import {
  java,
  javascript,
  c,
  python,
  jobs,
  benjamin,
  anne,
  apj,
  archer,
  alchemist,
  sherlock,
  dark,
  stephen,
  unlock,
  brief,
  blackholes,
} from "./images/index";
export const defaults = {
  Recommendations: [
    {
      name: "Eloquent JS",
      img_URL: javascript,
      auth: "Marijn Haverbeke",
      rating: "4.5/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "Steve Jobs: The Exclusive Biography",
      img_URL: jobs,
      auth: "Walter Isaacson ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "A Brief History Of Time: From Big Bang To Black Holes",
      img_URL: brief,
      auth: "Stephen Hawking ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "The Complete Novels of Sherlock Holmes",
      img_URL: sherlock,
      auth: "Arthur Conan Doyle",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
  ],
};

export const data = {
  Programming: [
    {
      name: "Eloquent JS",
      img_URL: javascript,
      auth: "Marijn Haverbeke",
      rating: "4.5/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "C language",
      img_URL: c,
      auth: "Darrel L. Graham",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "Java",
      img_URL: java,
      auth: "E Balagurusami",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "Python",
      img_URL: python,
      auth: "Ike Beck",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
  ],
  Biography: [
    {
      name: "The Autobiography of Benjamin Franklin",
      img_URL: benjamin,
      auth: "Benjamin Franklin",
      rating: "4.5/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "The Diary of a Young Girl",
      img_URL: anne,
      auth: "Anne Frank",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "Wings of Fire: An Autobiography of Abdul Kalam",
      img_URL: apj,
      auth: " A. P. J. Abdul Kalam ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "Steve Jobs: The Exclusive Biography",
      img_URL: jobs,
      auth: "Walter Isaacson ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
  ],
  Science: [
    {
      name: "Unlocking the Universe",
      img_URL: unlock,
      auth: "Stephen Hawking ",
      rating: "4.5/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "The Theory of Everything: The Origin and Fate of the Universe",
      img_URL: stephen,
      auth: "Stephen Hawking ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "Black Holes: The Reith Lectures",
      img_URL: blackholes,
      auth: "Stephen Hawking ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "A Brief History Of Time: From Big Bang To Black Holes",
      img_URL: brief,
      auth: "Stephen Hawking ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
  ],
  Fiction: [
    {
      name: "Dark Matter: A Mind-Blowing Twisted Thriller",
      img_URL: dark,
      auth: "Stephen Hawking",
      rating: "4.5/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "The Complete Novels of Sherlock Holmes",
      img_URL: sherlock,
      auth: "Arthur Conan Doyle",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "The Alchemist",
      img_URL: alchemist,
      auth: "Paulo Coelho ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
    {
      name: "The Archer",
      img_URL: archer,
      auth: "Paulo Coelho ",
      rating: "4/5",
      buy_link: "gdjjdgj",
    },
  ],
};
